### ISSUE TITLE
Create centralize options for resource and drive

### ISSUE THREAD

**Issue by hieulq** [cloudcomputinghust/CAL#10]
@daikk115 và @nhatbkk57 please re-think, write down and list all config options needed for resource and driver management such as: quota recheck thread cycle time, in-mem quota expired time...

@ntk148v please getting above list and create new centralize config option file for @daikk115 and @nhatbkk57

**Comment by hieulq** [comment]
@ntk148v this work item needs to be done in falcon_oslo_config

**Comment by ntk148v** [comment]
@hieulq i got it. this work will be done soon.

**Comment by daikk115** [comment]
With driver, I proposed setup all driver config in one file driver.py. For instance:

[openstack1]
enable=True
driver_name=OPENSTACK1
auth_url = http://controller:35357/v3
project_domain_name = default
user_domain_name = default
project_name = service
username = nova
password = NOVA_PASS

[aws1]
enable=True
driver_name=AWS1
aws_access_key_id = your_key_id
aws_secret_access_key = your_access_key

[openstack2]
enable=False

**Comment by hieulq** [comment]
@daikk115 This seems impossible for @ntk148v to implement these config options for you. Your proposal is dynamic config options for cloud vendor drivers but the centralize config is just for static config options.

**Comment by ntk148v** [comment]
@daikk115  i think we have a misunderstanding here. This issue is about static config options, basic one. Like timeout, expired_time,.... Another thing, if u want to implement your configs, u have to put it in the file called driver.conf, then i can load it. So give me your config options as soon as you can, @daikk115 @nhatbkk57 :))

**Comment by nhatbkk57** [comment]
@ntk148v i have discussions with @daikk115 about config option. That above config is only config of each cloud for check-active action. About check quota config, as @hieulq suggested, we've imagined 2 basic options:
re_check_cycle_time  - time init: min (eg: re_check_cycle = 2)
expired_time - time init: min (eg: expired_time = 15)

p/s: i still have no more idea about them.

**Comment by hieulq** [comment]
@ntk148v please implement the initiation of above 2 config options suggested by @nhatbkk57 
Keep thinking and we can fullfill the option list we need in the future, guys.

**Comment by ntk148v** [comment]
I implemented, but can u give me some descriptions about these options? For fill 'help' @daikk115 @nhatbkk57

**Comment by hieulq** [comment]
@ntk148v remember another validate for option (min, max..) such as:
`class IntOpt(Opt):

    """Option with Integer type

    Option with ``type`` :class:`oslo_config.types.Integer`

    :param name: the option's name
    :param min: minimum value the integer can take
    :param max: maximum value the integer can take
    :param \*\*kwargs: arbitrary keyword arguments passed to :class:`Opt`

    .. versionchanged:: 1.15

       Added *min* and *max* parameters.
    """

    def __init__(self, name, min=None, max=None, **kwargs):
        super(IntOpt, self).__init__(name, type=types.Integer(min, max),
                                     **kwargs)

or:

class StrOpt(Opt):
    """Option with String type

    Option with ``type`` :class:`oslo_config.types.String`

    :param name: the option's name
    :param choices: Optional sequence of valid values.
    :param quotes: If True and string is enclosed with single or double
                   quotes, will strip those quotes.
    :param regex: Optional regular expression (string or compiled
                  regex) that the value must match on an unanchored
                  search.
    :param ignore_case: If True case differences (uppercase vs. lowercase)
                        between 'choices' or 'regex' will be ignored.
    :param max_length: If positive integer, the value must be less than or
                       equal to this parameter.
    :param \*\*kwargs: arbitrary keyword arguments passed to :class:`Opt`

    .. versionchanged:: 2.7
       Added *quotes* parameter

    .. versionchanged:: 2.7
       Added *regex* parameter

    .. versionchanged:: 2.7
       Added *ignore_case* parameter

    .. versionchanged:: 2.7
       Added *max_length* parameter
    """

    def __init__(self, name, choices=None, quotes=None,
                 regex=None, ignore_case=None, max_length=None, **kwargs):
        super(StrOpt, self).__init__(name,
                                     type=types.String(
                                         choices=choices,
                                         quotes=quotes,
                                         regex=regex,
                                         ignore_case=ignore_case,
                                         max_length=max_length),
                                     **kwargs)

and:

class IPOpt(Opt):

    """Opt with IPAddress type

    Option with ``type`` :class:`oslo_config.types.IPAddress`

    :param name: the option's name
    :param version: one of either ``4``, ``6``, or ``None`` to specify
       either version.
    :param \*\*kwargs: arbitrary keyword arguments passed to :class:`Opt`

    .. versionadded:: 1.4
    """

    def __init__(self, name, version=None, **kwargs):
        super(IPOpt, self).__init__(name, type=types.IPAddress(version),
                                    **kwargs)`

Please see the definition of these classes in oslo_config/cfg.py file.

**Comment by ntk148v** [comment]
@hieulq yes, i knew these validates. But i have to know these config options deeply, for e.x, `re_check_cycle_time`, what is this used for? If i know, i can define another validates for this. So, please, give me some informations about it, guys.

**Comment by nhatbkk57** [comment]
@ntk148v re_check_cycle_time is option which is used by re-check thread to re-check quota of each driver (may be re-check active state also). For example: "re_check_cycle_time=2" means re-check thread will re-update quota of each driver per 2 mins.
And about "expired_time=15" means if the  time from last_time_update (attribute of quota object of driver), that driver quota was updated (by any ways: re-check thread after process action ...) at, to now is longer than 15 mins, the driver quota will be updated.

**Comment by ntk148v** [comment]
[Updated](https://github.com/cloudcomputinghust/CAL/commit/700b10150c42d6398c74fc40bf3f993281a11972)

**Comment by hieulq** [comment]
Look reasonable, we will first init with above 2 config options and add more if need.
