### ISSUE TITLE
Add coverage test to tox

### ISSUE THREAD

**Issue by hieulq** [cloudcomputinghust/CAL#14]
@ntk148v Please investigate code coverage test config in tox and implement to CAL. We will use the coverage test result to find out how many LOC are not covered then aim to provide enough unit tests for them.
Reference:
https://github.com/openstack/nova/blob/master/.coveragerc
and
https://github.com/openstack/nova/blob/master/tox.ini#L72

**Comment by ntk148v** [comment]
Updated! [Branch coverage](https://github.com/cloudcomputinghust/CAL/tree/coverage)

**Comment by hieulq** [comment]
@ntk148v I have finished the rest of your work.
@cloudcomputinghust/cal from now, every commits to repo must pass at least 4 phase: py27, py34, pep8 and coverage test. I will upload the coverage test of CAL code later.
