### ISSUE TITLE
Create singleton interface for CAL libs

### ISSUE THREAD

**Issue by hieulq** [cloudcomputinghust/CAL#15]
We need to implement a singleton manager for CAL lib which used by another app.

**Comment by hieulq** [comment]
@ntk148v remember to put your progress in this issue's comment, dude.

**Comment by hieulq** [comment]
@ntk148v ping?

**Comment by ntk148v** [comment]
@hieulq: i still work on this :( Currently, i try to increase coverage percent, then we can merge my new branch. But, it is still lower than 65.741%. If we finish resource client, we can up to at least 70%. So, can we skip coverage problem, merge and update it later?

**Comment by hieulq** [comment]
@ntk148v ok fine, go ahead and merge it

**Comment by hieulq** [comment]
@ntk148v remember writing doc about the case study of using cal-lib.

**Comment by hieulq** [comment]
@ntk148v ping
