### ISSUE TITLE
Implement QuotaAbstract class based on AWS and OpS concept

### ISSUE THREAD

**Issue by hieulq** [cloudcomputinghust/CAL#18]
Clone from trello tasks.

**Comment by hieulq** [comment]
@daikk115 @nhatbkk57 we are missing the deadline for this issue, right?

**Comment by nhatbkk57** [comment]
I just forgot it :(.

Vào 29-07-2016 16:58, "Hieu LE" <notifications@github.com> đã viết:

**Comment by hieulq** [comment]
@daikk115 Implement from @nhatbkk57 doc in following link: https://github.com/cloudcomputinghust/CAL/blob/resource/docs/network_nhathqh/abstract_quota.md

**Comment by hieulq** [comment]
@daikk115 ping

**Comment by daikk115** [comment]
@hieulq : I will push QuotaAbstact Class immediately

**Comment by daikk115** [comment]
@nhatbkk57 : Why did I see allocation_pools of a network in your survey?

**Comment by hieulq** [comment]
@nhatbkk57 answert @daikk115 's question and help him push ASAP

**Comment by nhatbkk57** [comment]
@hieulq Sure, i disussed with @daikk115  about this a few days ago.
