### ISSUE TITLE
About Quota Abtraction???

### ISSUE THREAD

**Issue by nhatbkk57** [cloudcomputinghust/CAL#21]
@hieulq @daikk115 
I've surveyed about quota of OPS Mitaka and AWS EC2. Generally, both of them display for user quite clearly and fully about quota. However, each cloud's quota have significant characteritics.

For example, VPC in EC2 (only 5 VPCs each region and 200 subnets per VPC)  in while OPS has large number of Network .... Assuming that 1 subnet in EC2 is same 1 network + 1 subnet in OPS in a definition:"network", so CIDRs of EC2 will be much more limited than OPS.

In other side, EC2 have some function which required payment.

So, what should i handle those issues?

**Comment by hieulq** [comment]
@nhatbkk57 firstly, can you list all quota type that do not charge any fee?
Second, as discuss earlier, we should grad all common item between cloud providers, so I think you should (again) survey and make a list of quota.

**Comment by nhatbkk57** [comment]
@hieulq i've complete it and will push the doc soon.

**Comment by nhatbkk57** [comment]
i'm going to complete soon!

2016-08-03 15:40 GMT+07:00 Hieu LE <notifications@github.com>:

**Comment by hieulq** [comment]
@nhatbkk57 Please write down your doc (or commit id of your doc here) and close issue.

**Comment by nhatbkk57** [comment]
https://github.com/cloudcomputinghust/CAL/blob/resource/docs/network_nhathqh/abstract_quota.md
