### ISSUE TITLE
Neutron client is still not working on Mitaka release.

### ISSUE THREAD

**Issue by daikk115** [cloudcomputinghust/CAL#23]
I'm stuck on upgrading driver from Kilo to Mitaka. 
I have tried a few ways to create/list network :

- follow [github neutron client](https://github.com/openstack/python-neutronclient/blob/stable/mitaka/doc/source/usage/library.rst): 
  + error : neutronclient.common.exceptions.Unauthorized: {"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}
- try to use auth_url with v3 like public endpoint : auth_url = http://controller:5000/v3 like [installation guide](http://docs.openstack.org/mitaka/install-guide-ubuntu/keystone-services.html)
  + error : neutronclient.common.exceptions.Unauthorized: {"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}

**Comment by hieulq** [comment]
@daikk115 please upload your test code in new branch or on your fork repo for re-produce the error

**Comment by daikk115** [comment]
My test is still here, on branch mitaka: 
https://github.com/daikk115/test-neutronclient/tree/mitaka

**Comment by daikk115** [comment]
@nhatbkk57 Can you test my code on your OPS virtual machine?

**Comment by hieulq** [comment]
@daikk115 I will test your code and give feedback later.

**Comment by hieulq** [comment]
@daikk115 your code worked fine in my testbed environment (see attachment pic). Please recheck your environment.
![screenshot_4](https://cloud.githubusercontent.com/assets/1811182/17387814/42a08548-5a21-11e6-9383-7128eddd4cf9.png)

**Comment by daikk115** [comment]
@hieulq Hum!! I'm tried to run my code on two OPS evironment but It didn't work.  
Let's me try again on other environments.

**Comment by hieulq** [comment]
@daikk115 Fix it ASAP or kneel before me in this Sunday.

**Comment by daikk115** [comment]
@hieulq  I must to reopen this issue because I just have tested on OPS node 16 of HPCC, but It's still not working. In my opinion, devstack fixed this issue or your OPS is not mitaka release. 

![screenshot from 2016-08-04 23 19 00](https://cloud.githubusercontent.com/assets/10351187/17409675/6fdf7946-5a9a-11e6-9656-6a6cc541bdbe.png)

**Comment by hieulq** [comment]
@daikk115 can you recheck with keystone api v2?

**Comment by hieulq** [comment]
@daikk115 you should recheck all your env, below is the test of your code in a new machine running OpenStack devstack mitaka
![screenshot_1](https://cloud.githubusercontent.com/assets/1811182/17432903/e75a27c8-5b2b-11e6-90fc-8519593a4c20.png)

**Comment by daikk115** [comment]
@hieulq 
Of course, I will recheck them.
But I mean maybe devstack has fixed our problem.  Github neutron is updated day by day meanwhile "apt-get install neutron... * is not built immediately.

**Comment by daikk115** [comment]
@hieulq : I think we have some things different between devstack and real env. 

Because, in devstack - mitaka release, I see:

daidv@ubuntu:~$ openstack endpoint list | grep neutron
| 2beefef7814e42b08146dbbe3bba940e | RegionOne | neutron      | network        | True    | internal  | http://192.168.248.164:9696/                   |
| 4cea69fff42c41d99ee184b31c7ab5d8 | RegionOne | neutron      | network        | True    | public    | http://192.168.248.164:9696/                   |
| 5d2f7982527645329deeb19dfff30e1a | RegionOne | neutron      | network        | True    | admin     | http://192.168.248.164:9696/                   |
daidv@ubuntu:~$ openstack endpoint list | grep keystone
| 473bede317ae4ec5bd18fde1ca932cc8 | RegionOne | keystone     | identity       | True    | admin     | http://192.168.248.164:35357/v2.0              |
| b8cd47885f9d4eb083012fc9e850143a | RegionOne | keystone     | identity       | True    | internal  | http://192.168.248.164:5000/v2.0               |
| c29d4095fc7c44db80332d9aef25f1ac | RegionOne | keystone     | identity       | True    | public    | http://192.168.248.164:5000/v2.0   

But in OPS mitaka manual, endpoint is used with v3.

**Comment by daikk115** [comment]
I have tested on devstack and It worked well.

![image](https://cloud.githubusercontent.com/assets/10351187/17458994/bb578da6-5c51-11e6-9898-cde1071f92d2.png)

**Comment by hieulq** [comment]
@daikk115 how about ops client approach?

**Comment by daikk115** [comment]
@hieulq : Actually, I have a glance at python-openstackclient and also osc-lib. But I'm still not know how to use them.

**Comment by hieulq** [comment]
@daikk115 what are your issues? why didn't you push them here?

**Comment by daikk115** [comment]
Yesterday, I read osc-lib and try to understand this Class which I think we can use as a client with post, get,... , so we need create Session follow [this](http://docs.openstack.org/developer/keystoneauth/using-sessions.html) but I have not yet try it.

Otherwise, I think [clientmanager](https://github.com/openstack/osc-lib/blob/master/osc_lib/clientmanager.py) module can do everything we want, but I still don't understand it.

**Comment by hieulq** [comment]
@daikk115 then try it ASAP

**Comment by daikk115** [comment]
@hieulq : I got it.

I found this commit https://review.openstack.org/#/c/92390/ and I have exactly way to connect keystone v3 and other client with auth v3. Poor me, I don't know why did I see it before.

Summary:

- Create  a session follow:

  + http://docs.openstack.org/developer/python-keystoneclient/authentication-plugins.html#v3-identity-plugins
  + https://github.com/openstack/python-keystoneclient/blob/master/doc/source/using-api-v3.rst
- Create a client, for instances:
  + keystone = client.Client(session=sess)
  + neutron = client.Client(session=sess)

**Comment by hieulq** [comment]
@daikk115 have you pushed your code yet?

**Comment by daikk115** [comment]
@hieulq : Yes, I have.  You can see some changes like here: https://github.com/cloudcomputinghust/CAL/blob/resource/cal/v1/network/drivers/openstack_network.py 

But some functions didn't really implement such as get_firewall, get_internet_gateways, etc. because I tryed on openstack  neutronclient but it's still not working meanwhile neutronclient really have the function is called list_firewalls. 

These are all of attribute and function of neutronclient that I used to saved by dir() function: https://github.com/daikk115/test-neutronclient/blob/authentication_v3/neutron_client_attribute.md
