### ISSUE TITLE
CALLib Problem - Dynamic Constructor

### ISSUE THREAD

**Issue by ntk148v** [cloudcomputinghust/CAL#25]
Hi guys, i get stuck at callib: 
- I have `cal/client.py` ,define method `def Client`, that will return 1 instance of resource-side-client class `cal/v1/network/client.py`. For ex:

```python

   from cal import client
   client = client.Client('1.0.0', 'network', 'OpenStack') # will return instance of Network client class.
 ```

- `cal/v1/<resource>/client.py` have class Client - an interface of provider driver(for ex, `...network/driver/openstack.py`, class OpenStack must be implement that Client). So, you can use callib like:

```python

   client = client.Client('1.0.0', 'network', 'OpenStack')
   client.create_network(*args)
```

---> Problem: this line `client.create_network(*args)` will call exactly create_network method in Client interface, not OpenStackDriver, so it won't return or do anything. I asked @hieulq, and he told me about __dynamic constructor__.

For test, i have dynamic module:

```
     dynamic/
    ├── a1.py
    ├── a2.py
    ├── a.py
    └── __init__.py
```

In `a.py`:

```python

    class A:
        a_class = a1.A1 # must import a1
        x = a_class()
```

In a1.py:

```python

    class A1(a.A): # must import a
        pass
```

--> I get *circular dependent imports*.

**Comment by hieulq** [comment]
@ntk148v sorry for wrong statement, A1 and A2 must inherit from interface provider and A is test class.
Below are example ('cause you are too noisy):
interface class Shit in shit.py
`import six
import abc


@six.add_metaclass(abc.ABCMeta)
class Shit(object):

    @abc.abstractmethod
    def pee(self, s):
        pass
`

3 provider Kien, Dai, Nhat in kien.py, dai.py and nhat.py:
kien.py
`import shit


class Kien(shit.Shit):

    def pee(self, s):
        print("Kien pee " + s)
`

dai.py
`import shit


class Dai(shit.Shit):

    def pee(self, s):
        print("Dai pee " + s)`

nhat.py
`import shit


class Nhat(shit.Shit):

    def pee(self, s):
        print("Nhat pee " + s)`

main test class
`import kien
import dai
import nhat


class Test(object):
    def __init__(self, cls):
        self._class = cls
        self.poo = self._class()

    def pee(self, s):
        self.poo.pee(s)

if __name__ == '__main__':
    slave = input("Show your name: ")
    if slave == "Kien":
        tmp = Test(kien.Kien)
    elif slave == "Dai":
        tmp = Test(dai.Dai)
    elif slave == "Nhat":
        tmp = Test(nhat.Nhat)

    tmp.pee("a big poo!")
`

output:
![screenshot_3](https://cloud.githubusercontent.com/assets/1811182/17611607/0d8c6efa-6073-11e6-87c8-1d7105d09f0d.png)

**Comment by ntk148v** [comment]
@daikk115 @nhatbkk57  check this example. :))  Then i will close this issue.
