### ISSUE TITLE
Dynamic Loading Module

### ISSUE THREAD

**Issue by ntk148v** [cloudcomputinghust/CAL#26]
[Hieu LE]: let's define all path to cal driver and resource via config or entry point.

and DO NOT HARD CODED ANYMORE.

**Comment by ntk148v** [comment]
@hieulq Done with the last 3 commits in callib branch.

- [commit 1](https://github.com/cloudcomputinghust/CAL/commit/68092b9af4bd9829e09a7385d6169749e01d4ead) 
- [commit 2](https://github.com/cloudcomputinghust/CAL/commit/b6f9089f841801cf1932b93c17f8449bc31d771c)
- [commit 3](https://github.com/cloudcomputinghust/CAL/commit/df788e5ef35bbb85a704a9340d94f52bfcaa7982)

**Comment by hieulq** [comment]
@ntk148v pong, reviewing!

**Comment by hieulq** [comment]
@ntk148v good job, seems that we need to improve the test case and examples of CAL. I'm gonna close this issue and move to the next issue with examples.

Thanks for your efforts, great works!
