### ISSUE TITLE
Rename driver module & Use ABC for base class

### ISSUE THREAD

**Issue by ntk148v** [cloudcomputinghust/CAL#28]
@daikk115 : you should rename your network driver. 

- `cal/v1/network/drivers/network_driver.py` --> `cal/network/drivers/base.py`. In that, for ex: `NetworkDriver` --> `BaseDriver`. Then use ABC to enforce that derived classes implement particular methods from the base class. Without ABC we’d only get a NotImplementedError if a missing method is actually called. Being notified about missing methods at instantiation time is a great advantage. It makes it harder for everyone to write invalid subclasses. For ex, you can refer [this class](https://github.com/cloudcomputinghust/CAL/blob/callib/cal/v1/network/drivers/base.py)

- `cal/v1/network/drivers/openstack_network.py` --> `cal/v1/network/drivers/openstack.py`. I think suffix `_network` is unnecessary in this case.

**Comment by hieulq** [comment]
@daikk115 ping

**Comment by hieulq** [comment]
@daikk115 let's update the code and make this merged soon.

**Comment by hieulq** [comment]
@daikk115 ping, close this issue?
