### ISSUE TITLE
How to get internet gateways via neutronclient? 

### ISSUE THREAD

**Issue by daikk115** [cloudcomputinghust/CAL#33]

**Comment by daikk115** [comment]
@nhatbkk57 : Please help me. I wonder what is internet gateways in network quota? And how to get them via python-neutronclient package?

**Comment by nhatbkk57** [comment]
Ok! an "internet gateway" means: 
In OPS:
- a router which connects to external network
- limit: according admin allocate for user  

In VPS: 
- a component or a resource that allows communication between instances in your VPC and the Internet
- Default limit: 5 Internet gateways per region


How to get them in OPS:
- count the numbers of router which have "external_gateway_info" being not null look like below dict
"external_gateway_info": {
                "enable_snat": true,
                "external_fixed_ips": [
                    {
                        "ip_address": "172.24.4.3",
                        "subnet_id": "b930d7f6-ceb7-40a0-8b81-a425dd994ccf"
                    },
                ],
                "network_id": "ae34051f-aa6c-4c75-abf5-50dc9ac99ef3"
            },

**Comment by nhatbkk57** [comment]
@daikk115 can you create a router connecting to the external network and an internal network and create another only connecting to internal network?? and then send me the json response???

**Comment by daikk115** [comment]
@nhatbkk57 : please connect to bkcloud16 via ssh. I have some test code in /home/bkcloud16/test-neutronclient.(byobu)

**Comment by hieulq** [comment]
@daikk115 ping, close this issue?
