### ISSUE TITLE
db type could not be determined

### ISSUE THREAD

**Issue by daikk115** [cloudcomputinghust/CAL#37]
when I run testcase via tox, I faced a problem like:

"db type could not be determined
ERROR: InvocationError: '/home/daidv/GITHUB/CAL/.tox/py34/bin/oste"

I have resolved it by remove .testrepository/times.dbm file.
I do not know if this is the right way to fix it, but it really worked.

https://bugs.launchpad.net/testrepository/+bug/1229445

**Comment by ntk148v** [comment]
Read tox.ini before create issue plz.

**Comment by daikk115** [comment]
I think you should push this issue before :D Instead of every time I got a bug, I must to walk around our code and try to find a comment which it help us fix bug.

**Comment by ntk148v** [comment]
You don't need to 'walk around our code', nobody do it if they focus on project. Problem with tox - read tox.ini file, that's all. So i think creating any issue is unnecessary. That's my opinion.

**Comment by hieulq** [comment]
@daikk115 there are some issues with tox py34, so you need to run py34 tests first, then go to py27.
