### ISSUE TITLE
Merge code from abstract network driver/resource into master

### ISSUE THREAD

**Issue by hieulq** [cloudcomputinghust/CAL#40]
@daikk115 aka Dai The Fallen:
As mentioned last week, we have missed the deadline for this task about 2 weeks ago.

Push the code ASAP, or kneel before me and sacrifice bim-bim.

@ntk148v help him pushing the pussy code ASAP.

**Comment by daikk115** [comment]
@hieulq : I just make a pull request. Please review it for me. Thanks.

**Comment by hieulq** [comment]
@daikk115 reviewed! check my comments, and sorry this issue is still alive (not closed yet)
