### ISSUE TITLE
Around config file format

### ISSUE THREAD

**Issue by daikk115** [cloudcomputinghust/CAL#47]
Now, config file format is created by me look like [this](https://github.com/cloudcomputinghust/CAL/blob/update_driver/calplus/tests/fake_config_file.conf)

@hieulq wonder what format is better than that for developer can be easier to coding.

It should be debate in next meeting.

**Comment by hieulq** [comment]
@daikk115 sure

**Comment by hieulq** [comment]
@daikk115 got consensus now, send another PR based on our conclusion.
