### ISSUE TITLE
Thay đổi test case theo falcon

### ISSUE THREAD

**Issue by hieulq** [cloudcomputinghust/CAL#8]
@ntk148v cần chạy tox -e pep8 và py27, py34 trước khi push code.
Hiện tại travis CI đang báo lỗi khi run unit test, Kiên vào fix lại test wsgi nhé.

**Comment by hieulq** [comment]
link travis: https://travis-ci.org/cloudcomputinghust/CAL/builds/144649311

**Comment by ntk148v** [comment]
@hieulq : Đã fix thành công ạ. Link [travis](https://travis-ci.org/cloudcomputinghust/CAL/builds/144901013)
